// examples/svelte/src/routes/+page.svelte
<script lang="ts">
import { client } from "$lib/better-agent/client";
import { createAgentChat } from "@better-agent/client/svelte";

const chat = createAgentChat(client, {
    agent: "anthropic",
    conversationId: "main",
    hydrateFromServer: true,
    resume: true,
});

let input = $state("");
</script>

<main class="min-h-screen bg-[color:var(--background)] px-4 py-6 text-[color:var(--foreground)] sm:px-6 sm:py-8">
  <section class="mx-auto grid max-w-3xl gap-4">
    <header class="grid gap-3">
      <p class="m-0 font-mono text-[11px] uppercase tracking-[0.08em] text-[color:var(--muted)]">
        Generated by Better Agent
      </p>
      <h1 class="m-0 text-[1.85rem] font-semibold tracking-[-0.05em] text-white sm:text-[2.2rem]">
        SvelteKit Starter Chat
      </h1>
      <div class="flex items-center gap-2 border border-[color:var(--border)] bg-[color:var(--panel)] px-3 py-2 font-mono text-[11px] uppercase tracking-[0.2em] text-[color:var(--muted)]">
        <span class="text-white/55">&gt;_</span>
        <span class="text-white/78">/agents/openai</span>
      </div>
    </header>

    <section class="grid gap-3 border border-[color:var(--border)] bg-[color:var(--panel)] p-3 sm:p-4">
      <div class="flex items-center justify-between gap-3 font-mono text-[11px] uppercase tracking-[0.22em] text-[color:var(--muted)]">
        <span>conversation main</span>
        <span>{$chat.status}</span>
      </div>

      <section class="grid min-h-[320px] gap-3 border border-[color:var(--border)] bg-[color:var(--panel-muted)] p-3" aria-live="polite">
        {#if $chat.messages.length === 0}
          <div class="grid place-items-center border border-dashed border-[color:var(--border)] px-4 py-12 text-center text-sm leading-6 text-[color:var(--muted)]">
            No messages yet.
          </div>
        {:else}
          <div class="grid content-start gap-3 self-start">
            {#each $chat.messages as message (message.localId)}
              <article class={`max-w-[88%] border px-2.5 py-2 text-sm leading-[1.55] ${message.role === "user" ? "ml-auto border-[color:var(--border-strong)] bg-white text-black" : "border-[color:var(--border)] bg-black text-[color:var(--foreground)]"}`}>
                <p class={`m-0 font-mono text-[9px] uppercase tracking-[0.18em] ${message.role === "user" ? "text-black/55" : "text-[color:var(--muted)]"}`}>
                  {message.role}
                </p>
                <p class="m-0 mt-1.5 whitespace-pre-wrap">
                  {message.parts.filter((part) => part.type === "text").map((part) => part.text).join("\n") || "No text content"}
                </p>
              </article>
            {/each}
          </div>
        {/if}
      </section>

      <form
        class="grid gap-3"
        onsubmit={async (event) => {
          event.preventDefault();
          if ($chat.status === "submitted" || $chat.status === "streaming") {
            chat.stop();
            return;
          }
          const value = input.trim();
          if (!value) return;
          input = "";
          await chat.sendMessage(value);
        }}
      >
        <textarea bind:value={input} placeholder="Ask something..." aria-label="Message" class="min-h-[96px] w-full resize-none border border-[color:var(--border)] bg-black px-3 py-2.5 text-sm leading-6 text-[color:var(--foreground)] outline-none transition placeholder:text-[color:var(--muted)] focus:border-[color:var(--border-strong)]"></textarea>
        <div class="flex flex-wrap items-center justify-end gap-3">
          <div class="flex items-center gap-2">
            <button type="button" onclick={() => chat.stop()} disabled={$chat.status !== "submitted" && $chat.status !== "streaming"} class="border border-[color:var(--border)] px-3 py-2 text-sm text-[color:var(--foreground)] transition hover:border-[color:var(--border-strong)] disabled:cursor-not-allowed disabled:opacity-40">Stop</button>
            <button type="submit" disabled={$chat.status === "submitted" || $chat.status === "streaming" || input.trim().length === 0} class="border border-white bg-white px-3 py-2 text-sm font-medium text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-40">{$chat.status === "streaming" || $chat.status === "submitted" ? "Streaming" : "Send"}</button>
          </div>
        </div>
        {#if $chat.error}
          <p class="m-0 border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">{$chat.error.message}</p>
        {/if}
        <div class="border-t border-[color:var(--border)] pt-3">
          <p class="m-0 font-mono text-[10px] uppercase tracking-[0.18em] text-[color:var(--muted)]">
            Docs
            <a href="https://www.better-agent.com/docs" target="_blank" rel="noreferrer" class="font-medium text-white/88">better-agent.com/docs</a>
          </p>
        </div>
      </form>
    </section>
  </section>
</main>

// examples/tanstack/src/routes/index.tsx
import { useAgent } from "@better-agent/client/react";
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { client } from "../better-agent/client";

function ChatPage() {
    const [input, setInput] = useState("");
    const { messages, status, error, sendMessage, stop } = useAgent(client, {
        agent: "anthropic",
        conversationId: "main",
        hydrateFromServer: true,
        resume: true,
    });

    return (
        <main className="min-h-screen bg-[color:var(--background)] px-4 py-6 text-[color:var(--foreground)] sm:px-6 sm:py-8">
            <section className="mx-auto grid max-w-3xl gap-4">
                <header className="grid gap-3">
                    <p className="m-0 font-mono text-[11px] uppercase tracking-[0.08em] text-[color:var(--muted)]">
                        Generated by Better Agent
                    </p>
                    <h1 className="m-0 text-[1.85rem] font-semibold tracking-[-0.05em] text-white sm:text-[2.2rem]">
                        TanStack Start Starter Chat
                    </h1>
                    <div className="flex items-center gap-2 border border-[color:var(--border)] bg-[color:var(--panel)] px-3 py-2 font-mono text-[11px] uppercase tracking-[0.2em] text-[color:var(--muted)]">
                        <span className="text-white/55">&gt;_</span>
                        <span className="text-white/78">/agents/openai</span>
                    </div>
                </header>
                <section className="grid gap-3 border border-[color:var(--border)] bg-[color:var(--panel)] p-3 sm:p-4">
                    <div className="flex items-center justify-between gap-3 font-mono text-[11px] uppercase tracking-[0.22em] text-[color:var(--muted)]">
                        <span>conversation main</span>
                        <span>{status}</span>
                    </div>
                    <section
                        className="grid min-h-[320px] gap-3 border border-[color:var(--border)] bg-[color:var(--panel-muted)] p-3"
                        aria-live="polite"
                    >
                        {messages.length === 0 ? (
                            <div className="grid place-items-center border border-dashed border-[color:var(--border)] px-4 py-12 text-center text-sm leading-6 text-[color:var(--muted)]">
                                No messages yet.
                            </div>
                        ) : (
                            <div className="grid content-start gap-3 self-start">
                                {messages.map((message) => (
                                    <article
                                        key={message.localId}
                                        className={`max-w-[88%] border px-2.5 py-2 text-sm leading-[1.55] ${
                                            message.role === "user"
                                                ? "ml-auto border-[color:var(--border-strong)] bg-white text-black"
                                                : "border-[color:var(--border)] bg-black text-[color:var(--foreground)]"
                                        }`}
                                    >
                                        <p
                                            className={`m-0 font-mono text-[9px] uppercase tracking-[0.18em] ${
                                                message.role === "user"
                                                    ? "text-black/55"
                                                    : "text-[color:var(--muted)]"
                                            }`}
                                        >
                                            {message.role}
                                        </p>
                                        <p className="m-0 mt-1.5 whitespace-pre-wrap">
                                            {message.parts
                                                .filter(
                                                    (
                                                        part,
                                                    ): part is Extract<
                                                        (typeof message.parts)[number],
                                                        { type: "text" }
                                                    > => part.type === "text",
                                                )
                                                .map((part) => part.text)
                                                .join("\n") || "No text content"}
                                        </p>
                                    </article>
                                ))}
                            </div>
                        )}
                    </section>
                    <form
                        className="grid gap-3"
                        onSubmit={async (event) => {
                            event.preventDefault();
                            if (status === "submitted" || status === "streaming") {
                                stop();
                                return;
                            }
                            const value = input.trim();
                            if (!value) return;
                            setInput("");
                            await sendMessage(value);
                        }}
                    >
                        <textarea
                            value={input}
                            onChange={(event) => setInput(event.target.value)}
                            placeholder="Ask something..."
                            aria-label="Message"
                            className="min-h-[96px] w-full resize-none border border-[color:var(--border)] bg-black px-3 py-2.5 text-sm leading-6 text-[color:var(--foreground)] outline-none transition placeholder:text-[color:var(--muted)] focus:border-[color:var(--border-strong)]"
                        />
                        <div className="flex flex-wrap items-center justify-end gap-3">
                            <div className="flex items-center gap-2">
                                <button
                                    type="button"
                                    onClick={() => stop()}
                                    disabled={status !== "submitted" && status !== "streaming"}
                                    className="border border-[color:var(--border)] px-3 py-2 text-sm text-[color:var(--foreground)] transition hover:border-[color:var(--border-strong)] disabled:cursor-not-allowed disabled:opacity-40"
                                >
                                    Stop
                                </button>
                                <button
                                    type="submit"
                                    disabled={
                                        status === "submitted" ||
                                        status === "streaming" ||
                                        input.trim().length === 0
                                    }
                                    className="border border-white bg-white px-3 py-2 text-sm font-medium text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-40"
                                >
                                    {status === "submitted" || status === "streaming"
                                        ? "Streaming"
                                        : "Send"}
                                </button>
                            </div>
                        </div>
                        {error ? (
                            <p className="m-0 border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">
                                {error.message}
                            </p>
                        ) : null}
                        <div className="border-t border-[color:var(--border)] pt-3">
                            <p className="m-0 font-mono text-[10px] uppercase tracking-[0.18em] text-[color:var(--muted)]">
                                Docs{" "}
                                <a
                                    href="https://www.better-agent.com/docs"
                                    target="_blank"
                                    rel="noreferrer"
                                    className="font-medium text-white/88"
                                >
                                    better-agent.com/docs
                                </a>
                            </p>
                        </div>
                    </form>
                </section>
            </section>
        </main>
    );
}

export const Route = createFileRoute("/")({
    component: ChatPage,
});
